server:
  servlet:
    contextPath: /TransferAPI/${info.app.version}

info:
  app:
    name: transfer-api-service
    version: v1
    description: TransferAPI

spring:
  application:
    name: ${info.app.name}
  h2:
    console:
     enabled: true
     path: /h2 
  datasource:
     driverClassName: org.h2.Driver
     url: jdbc:h2:mem:testdb
     username: SA
     password: 
       

logging:
   level:
    root: debug
    com.core.banking: error                   
    
